version: '3'
services:
  python-app:
    image: javidi/python-docker:latest
    container_name: python-app
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./data/src:/app
      - ./data/supervisord.conf:/etc/supervisord.conf